apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"PersistentVolumeClaim","apiVersion":"v1","metadata":{"name":"metrics-cassandra-1","creationTimestamp":null,"labels":{"metrics-infra":"hawkular-cassandra"}},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}}},"status":{}}'
  creationTimestamp: 2017-11-17T09:32:34Z
  labels:
    metrics-infra: hawkular-cassandra
  name: metrics-cassandra-1
  namespace: openshift-infra
  resourceVersion: "216718"
  selfLink: /api/v1/namespaces/openshift-infra/persistentvolumeclaims/metrics-cassandra-1
  uid: 3e344046-cb7a-11e7-8e84-00505685f56e
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status:
  phase: Pending
